triggers:
- envs: []
  name: transform and predict
  pipeline_uuid: transform_and_predict
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-03-04 11:59:00
  status: active
  variables: {}
