triggers:
- envs: []
  name: elven sea
  pipeline_uuid: transform_and_predict
  schedule_interval: null
  schedule_type: null
  settings: null
  sla: null
  start_time: null
  status: inactive
  variables: null
- envs: []
  name: transform and predict
  pipeline_uuid: transform_and_predict
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-03-04 11:59:00
  status: inactive
  variables: {}
